# Generated by Django 4.2.11 on 2025-06-29 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claimitem',
            name='type',
        ),
        migrations.AddField(
            model_name='claimitem',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claim_items', to='claims.expenseclaim'),
        ),
    ]
