# Generated by Django 4.2.11 on 2025-06-29 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0002_remove_claimitem_type_claimitem_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenseclaim',
            name='status',
        ),
        migrations.AlterField(
            model_name='claimitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=50),
        ),
    ]
