# Generated by Django 5.2.3 on 2025-06-30 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0003_remove_expenseclaim_status_alter_claimitem_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claimitem',
            name='status',
        ),
        migrations.AddField(
            model_name='claimitem',
            name='type',
            field=models.CharField(choices=[('travel', 'Travel'), ('food', 'Food'), ('accommodation', 'Accommodation'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='expenseclaim',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=50),
        ),
    ]
